server:
  port: 7070
spring:
  application:
    name: hiring-process-7
  datasource:
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
# Camunda
camunda.bpm:
  admin-user:
    id: a
    password: a
  deployment-resource-pattern: "classpath*:/bpmn/*.bpmn,classpath*:/form/*.form"
  database:
    type: postgres
    schema-update: true
sendgrid:
    api-key: ${SENDGRID_API_KEY}
    from-email: ahmad.aldeeb@qeema.net
    from-name: Qeema
# Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
# Jaeger
  tracing:
    sampling:
      probability: 1.0
  observations:
    annotations:
      enabled: true
tracing:
  url: http://172.18.0.2:30001