FROM maven:3.9.6-eclipse-temurin-21 AS build
WORKDIR /app
COPY pom.xml .
RUN mvn dependency:go-offline
COPY src ./src
RUN mvn package spring-boot:repackage

FROM gcr.io/distroless/java21-debian12 AS run
# RUN chmod -R 777 /app
COPY --from=build /app/target/hiring-process-7.jar hiring-process-7.jar
ENTRYPOINT ["java", "-jar", "hiring-process-7.jar"]