FROM maven:3.9.6-eclipse-temurin-21 AS build
WORKDIR /app

COPY pom.xml .
RUN mvn dependency:go-offline

COPY src ./src
RUN mvn package spring-boot:repackage

RUN chmod -R 777 /app

ENTRYPOINT ["java", "-jar", "target/hiring-process-7.jar"]